### PR TITLE
Feature/divide

### PR DESCRIPTION
**Pull request by sauravsolanki**

### CODE REVIEW

**Comment by sauravsolanki** [comment]
I have added code to test for the divide. Kindly Please merge it.

**Comment by finalight** [comment]
conflict @sauravsolanki

**Comment by sauravsolanki** [comment]
Resolved.

**Comment by sauravsolanki** [comment]
I have resolved all error. Please merge.

**Comment by finalight** [comment]
conflict @sauravsolanki

**Comment by sauravsolanki** [comment]
Resolved.

**Pull request merged**
